### PR TITLE
[REVIEW] Initial Esspresso implementation

### PR DESCRIPTION
**Pull request by jaggernod**
Not adding Travis support as it has a cap of 3GB which is not enough for connected tests.

The connected tests can be run on a local machine for now.

### CODE REVIEW

**Comment by tehmou** [comment]
@jaggernod needs rebasing. Couldn't resolve the conflict, complains

`Warning:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (22.1.1) and test app (22.0.0) differ.`

**Comment by jaggernod** [comment]
DONE

**Comment by tehmou** [comment]
@jaggernod I think there is an actual problem with the Travis build.

`:app:lintFailed converting ECJ parse tree to Lombok for file /home/travis/build/tehmou/rx-android-architecture/app/src/main/java/com/tehmou/rxbookapp/data/DataStoreModule.java
java.lang.UnsupportedOperationException: Unknown ASTNode child: ReferenceExpression
	at lombok.ast.ecj.EcjTreeVisitor.visitOther(EcjTreeVisitor.java:368)`

**Comment by jaggernod** [comment]
The problem is not app:lintFailed. The new release of Lint is just more verbose about retrolambda.

The problem is that the connected test is not passing. Probably because animations are not disabled on the emulator. Will need to implement that.

**Pull request merged**
